# Generated by Django 5.0.1 on 2024-02-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blog_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
