# Generated by Django 5.0.1 on 2024-02-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_about_image_alter_blog_image_alter_car_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('percent', models.CharField(max_length=250)),
                ('speed', models.CharField(max_length=250)),
                ('insurance', models.CharField(max_length=250)),
                ('support', models.CharField(max_length=250)),
            ],
        ),
    ]
