# Generated by Django 5.0.1 on 2024-02-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_advantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='page_info',
            field=models.CharField(default='The best car is here', max_length=250),
        ),
        migrations.AddField(
            model_name='car',
            name='page_title',
            field=models.CharField(default='You will find a best car in our city', max_length=250),
        ),
    ]
