# Generated by Django 5.0.1 on 2024-02-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_car_page_info_car_page_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-date',)},
        ),
    ]
